---
tenants: # dynamic_key: network_services
  - name: GROQ
    mac_vrf_id_base: 2000
    vrfs:
      - name: groq-inside
        vrf_id: 800
        enable_mlag_ibgp_peering_vrfs: false
        address_families:
          - evpn
        l3_interfaces:
          - interfaces: [ Ethernet1, Ethernet2, Ethernet1, Ethernet1 ]
            ip_addresses: [ 1.1.1.0/31, 1.1.1.2/31, 1.1.1.1/31, 1.1.1.3/31 ]
            nodes: [ CE-01, CE-01, PE-07, PE-08 ]
          - interfaces: [ Ethernet1, Ethernet2, Ethernet2/1, Ethernet2/1 ]
            ip_addresses: [ 1.1.1.4/31, 1.1.1.6/31, 1.1.1.5/31, 1.1.1.7/31 ]
            nodes: [ CE-02, CE-02, PE-09, PE-10 ]
        bgp_peers:
          - ip_address: 1.1.1.1
            remote_as: 65800
            send_community: extended
            description: to-PE-07
            nodes:
              - CE-01
          - ip_address: 1.1.1.3
            remote_as: 65800
            send_community: extended
            description: to-PE-08
            nodes:
              - CE-01
          - ip_address: 1.1.1.0
            remote_as: 65800
            send_community: extended
            description: to-CE-01
            nodes:
              - PE-07
          - ip_address: 1.1.1.2
            remote_as: 65800
            send_community: extended
            description: to-CE-01
            nodes:
              - PE-08
          - ip_address: 1.1.1.5
            remote_as: 65800
            send_community: extended
            description: to-PE-09
            nodes:
              - CE-02
          - ip_address: 1.1.1.7
            remote_as: 65800
            send_community: extended
            description: to-PE-10
            nodes:
              - CE-02
          - ip_address: 1.1.1.4
            remote_as: 65800
            send_community: extended
            description: to-CE-02
            nodes:
              - PE-09
          - ip_address: 1.1.1.6
            remote_as: 65800
            send_community: extended
            description: to-CE-02
            nodes:
              - PE-10
#          - ip_address: 1.1.1.4
#            remote_as: 65900
#            send_community: extended
#            description: ebgp-to-pe-1
#            nodes:
#              - ce-2
#          - ip_address: 1.1.1.5
#            remote_as: 65801
#            send_community: extended
#            description: ebgp-to-ce-2
#            nodes:
#              - pe-1
        svis:
          - id: 100
            name: Vlan_100_groq_inside
            tags: [ CE-01 ]
            nodes:
              - node: CE-01
                enabled: true
                ip_address: 172.16.100.1/24
          - id: 200
            name: Vlan_200_groq_inside
            tags: [ CE-02 ]
            nodes:
              - node: CE-02
                enabled: true
                ip_address: 172.16.200.1/24
