---
- name: Validate Fabric Build
  hosts: MPLS_CORE
  connection: httpapi
  gather_facts: false

  tasks:
    - name: validate states on EOS devices
      ansible.builtin.import_role:
          name: arista.avd.eos_validate_state
  vars:
    use_anta: true
    save_catalog: true
    skipped_tests:
      - category: AvdTestHardware
        tests:
          - VerifyEnvironmentCooling
          - VerifyEnvironmentPower
          - VerifyTemperature
          - VerifyTransceiversManufacturers